// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crypto.sql

package cryptodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestPrice = `-- name: GetLatestPrice :one
SELECT id, exchange, coin_symbol, coin_price, trade_id, traded_at, created_at FROM crypto_prices
WHERE exchange = $1 AND coin_symbol = $2
ORDER BY traded_at DESC, id DESC
LIMIT 1
`

type GetLatestPriceParams struct {
	Exchange   string
	CoinSymbol string
}

func (q *Queries) GetLatestPrice(ctx context.Context, arg GetLatestPriceParams) (CryptoPrice, error) {
	row := q.db.QueryRow(ctx, getLatestPrice, arg.Exchange, arg.CoinSymbol)
	var i CryptoPrice
	err := row.Scan(
		&i.ID,
		&i.Exchange,
		&i.CoinSymbol,
		&i.CoinPrice,
		&i.TradeID,
		&i.TradedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertPrice = `-- name: InsertPrice :exec
INSERT INTO crypto_prices (exchange, coin_symbol, coin_price, trade_id, traded_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type InsertPriceParams struct {
	Exchange   string
	CoinSymbol string
	CoinPrice  pgtype.Numeric
	TradeID    *int64
	TradedAt   pgtype.Timestamptz
}

func (q *Queries) InsertPrice(ctx context.Context, arg InsertPriceParams) error {
	_, err := q.db.Exec(ctx, insertPrice,
		arg.Exchange,
		arg.CoinSymbol,
		arg.CoinPrice,
		arg.TradeID,
		arg.TradedAt,
	)
	return err
}

const listPricesForCoin = `-- name: ListPricesForCoin :many
SELECT id, exchange, coin_symbol, coin_price, trade_id, traded_at, created_at FROM crypto_prices
WHERE exchange = $1
  AND coin_symbol = $2
  AND (traded_at, id) < ($3::timestamptz, $4::bigint)
ORDER BY traded_at DESC, id DESC
LIMIT $5
`

type ListPricesForCoinParams struct {
	Exchange   string
	CoinSymbol string
	BeforeTime pgtype.Timestamptz
	BeforeID   int64
	MaxResults int32
}

func (q *Queries) ListPricesForCoin(ctx context.Context, arg ListPricesForCoinParams) ([]CryptoPrice, error) {
	rows, err := q.db.Query(ctx, listPricesForCoin,
		arg.Exchange,
		arg.CoinSymbol,
		arg.BeforeTime,
		arg.BeforeID,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CryptoPrice
	for rows.Next() {
		var i CryptoPrice
		if err := rows.Scan(
			&i.ID,
			&i.Exchange,
			&i.CoinSymbol,
			&i.CoinPrice,
			&i.TradeID,
			&i.TradedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
