// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crypto.sql

package cryptodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestPrice = `-- name: GetLatestPrice :one
SELECT id, coin_symbol, coin_price, created_at FROM crypto_prices
WHERE coin_symbol = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPrice(ctx context.Context, coinSymbol string) (CryptoPrice, error) {
	row := q.db.QueryRow(ctx, getLatestPrice, coinSymbol)
	var i CryptoPrice
	err := row.Scan(
		&i.ID,
		&i.CoinSymbol,
		&i.CoinPrice,
		&i.CreatedAt,
	)
	return i, err
}

const insertCryptoPrices = `-- name: InsertCryptoPrices :exec
INSERT INTO crypto_prices (coin_symbol, coin_price)
VALUES ($1, $2)
`

type InsertCryptoPricesParams struct {
	CoinSymbol string
	CoinPrice  pgtype.Numeric
}

func (q *Queries) InsertCryptoPrices(ctx context.Context, arg InsertCryptoPricesParams) error {
	_, err := q.db.Exec(ctx, insertCryptoPrices, arg.CoinSymbol, arg.CoinPrice)
	return err
}
