// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cryptodb

import (
	"database/sql"
)

type CryptoPrice struct {
	ID         int64
	CoinSymbol string
	CoinPrice  string
	CreatedAt  sql.NullTime
}
