// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cryptodb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CryptoPrice struct {
	ID         int64
	Exchange   string
	CoinSymbol string
	CoinPrice  pgtype.Numeric
	TradeID    *int64
	CreatedAt  pgtype.Timestamptz
}
